DROP SCHEMA IF EXISTS pizzaService;
CREATE SCHEMA pizzaService;
USE pizzaService;

CREATE TABLE Customer (
    CustomerID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    Gender VARCHAR(1) NOT NULL,
    Birthdate DATE NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Address VARCHAR(64)
);

CREATE TABLE CustomerAccount (
    CustomerAccountID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    Username VARCHAR(32) NOT NULL,
    Password VARCHAR(32) NOT NULL,
    PizzaCount INT NOT NULL DEFAULT 0,
    DiscountCode VARCHAR(16) DEFAULT NULL,
    FreeBirthdayPizza BOOLEAN NOT NULL DEFAULT FALSE,
    FreeBirthdayDrink BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE DiscountCode (
    DiscountCodeID INT PRIMARY KEY AUTO_INCREMENT,
    Code VARCHAR(16) NOT NULL,
    DiscountPercentage FLOAT NOT NULL,
    Used BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    CustomerID INT NOT NULL,
    Status VARCHAR(32) NOT NULL,
    OrderTime DATETIME NOT NULL,
    TotalPrice FLOAT NOT NULL,
    DeliveryTime DATETIME NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID)
);

CREATE TABLE DeliveryPerson (
    DeliveryPersonID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    PostalCode VARCHAR(6) NOT NULL,
    Availability BOOLEAN NOT NULL DEFAULT TRUE,
    CurrentOrderID INT DEFAULT NULL,
    UnavailableUntil DATETIME DEFAULT NULL
);

CREATE TABLE PostalCodeArea (
    PostalCodeAreaID INT PRIMARY KEY AUTO_INCREMENT,
    PostalCode VARCHAR(6) NOT NULL,
    City VARCHAR(32) NOT NULL,
    DeliveryPersonCount INT NOT NULL
);

CREATE TABLE Pizza (
    PizzaID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    Price FLOAT NOT NULL,
    Diet VARCHAR(32) DEFAULT NULL
);

CREATE TABLE Drink (
    DrinkID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    Price FLOAT NOT NULL
);

CREATE TABLE Dessert (
    DessertID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    Price FLOAT NOT NULL,
    Diet VARCHAR(32) DEFAULT NULL
);

CREATE TABLE OrderPizza (
    OrderPizzaID INT PRIMARY KEY AUTO_INCREMENT,
    PizzaID INT NOT NULL,
    OrderID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (PizzaID) REFERENCES Pizza(PizzaID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

CREATE TABLE OrderDrink (
    OrderDrinkID INT PRIMARY KEY AUTO_INCREMENT,
    DrinkID INT NOT NULL,
    OrderID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (DrinkID) REFERENCES Drink(DrinkID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

CREATE TABLE OrderDessert (
    OrderDessertID INT PRIMARY KEY AUTO_INCREMENT,
    DessertID INT NOT NULL,
    OrderID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (DessertID) REFERENCES Dessert(DessertID),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

CREATE TABLE Ingredient (
    IngredientID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(32) NOT NULL,
    Price FLOAT,
    Diet VARCHAR(32) DEFAULT NULL
);

CREATE TABLE PizzaIngredient (
    PizzaIngredientID INT PRIMARY KEY AUTO_INCREMENT,
    PizzaID INT NOT NULL,
    IngredientID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (PizzaID) REFERENCES Pizza(PizzaID),
    FOREIGN KEY (IngredientID) REFERENCES Ingredient(IngredientID)
);